config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :year, presence: true
  validates :category, presence: true
  validates :description, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @book = Book.all
        render :index
    end

    def show
        @book = Book.find(params[:id])
        render :show
    end

    def new
        @book = Book.new
        render :new
    end

    def create
        @book = Book.new(book_params)

        if @book.valid?
          @book.save
          redirect_to book_url(@book.id)
        end
    end
 
    def edit
        @book = Book.find(params[:id])
        render :edit
    end


    def update
        @book = Book.find(params[:id])

        if @book.update_attributes(book_params)
          redirect_to book_url(@book)
        else
          render :edit
        end
    end

    def destroy
    end


    private
      
      def book_params
        params.require(:book).permit(:title, :author, :category, :year, :description)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<% if action == :edit %>
  <% action_url = book_url(book) %>
<% else %>
  <% action_url = books_url %>
<% end %>

<form action="<%= action_url %>" method="post">
<% if action == :edit %>
  <input type="hidden" name="_method" value="PATCH">
<% end %>

  <label for="title">Title</label>
  <input id="title" type="text" name="book[title]" value="<%= book.title %>">
<br>
<br>
 <label for="author">Author</label>
  <input id="author" type="text" name="book[author]" value="<%= book.author %>">
<br>
<br>
   <label for="year">Year</label>
  <input id="Year" type="number" name="book[year]" value="<%= book.year %>">
<br>
<br>
    <label for="category">Category</label>
   <select name="book[category]">
       <option disabled <%= action == :new ? "selected" : "" %>>-- Please Select --</option>
       <option value="Science-Fiction" <%= @book.category == "Science-Fiction" ? "selected" : "" %>>Science-Fiction</option>
       <option value="Fantasy" <%= @book.category == "Fantasy" ? "selected" : "" %>>Fantasy</option>
       <option value="Mystery"<%= @book.category == "Mystery" ? "selected" : "" %>>Mystery</option>
       <option value="History"<%= @book.category == "History" ? "selected" : "" %>>History</option>
       <option value="Non-Fiction"<%= @book.category == "Non-Fiction" ? "selected" : "" %>>Non-Fiction</option>
       <option value="Autobiography"<%= @book.category == "Autobiography" ? "selected" : "" %>>Autobiography</option>
   </select>
<br>
<br>
   <label for="description">Description</label>
<br>
   <textarea name="book[description]">
    <%= book.description %>
   </textarea>
<br>
  <input type="submit" value="<%= action == :edit ? "Update Book" : "Add Book" %>">
</form>

<p><%= link_to("Back to Books", books_url) %> </p>

app/views/books/edit.html.erb
<h1>Edit Book Info</h1>

<%= render 'form', book: @book, action: :edit %>

app/views/books/index.html.erb
<h1>My Library App!</h1>
<ul>
    <% @book.each do |book| %>
        <li><%= link_to("#{book.title}", book_path(Book.find(book.id))) %></li>
    <% end  %>
</ul>
<p><%= link_to("Add a book", new_book_url) %>

app/views/books/new.html.erb
<h1>Add a book to the library!</h1>

<%= render 'form', action: :new, book: @book %>

app/views/books/show.html.erb
<h1>Book Information</h1>
<h2>Title: <%= @book.title %></h2>
<h3>Author: <%= @book.author %></h3>
<h3>Year: <%= @book.year %></h3>
<h3>Category: <%= @book.category %></h3>
<p>Description: <%= @book.description %></p>

<p><%= link_to("Back to books", books_url) %></p>
<p><%= link_to("Edit book", edit_book_url(@book))%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>